name: fluwer
description: A starter app for easily distributing apps.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - lib/image/issues.png
      - lib/image/issues_selected.png
      - lib/image/jobs.png
      - lib/image/jobs_selected.png
      - lib/image/packages.png
      - lib/image/packages_selected.png
      - lib/image/settings.png
      - lib/image/settings_selected.png